# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sort-External
version:      0.12
version_from: lib/Sort/External.pm
installdirs:  site
requires:
    Clone:                         0
    File::Temp:                    0.14
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
